CREATE SCHEMA CertWare;
USE CertWare;

CREATE TABLE Student(
	StudentID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    DOB DATE NOT NULL,
    PRIMARY KEY (StudentID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Courses(
	CourseID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CourseName VARCHAR(64) NOT NULL,
    isActive BOOLEAN DEFAULT 1,
    PRIMARY KEY (CourseID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Certifications(
	CertID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    CertName VARCHAR(64) NOT NULL,
    ValidMonths INT UNSIGNED NULL,
    CourseID INT UNSIGNED NOT NULL,
    PRIMARY KEY (CertID),
    INDEX idx_certs_course (CourseID),
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE StudentCertifications(
	StudentCertID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    StudentID INT UNSIGNED NOT NULL,
    CertID INT UNSIGNED NOT NULL,
	IssueDate DATE NOT NULL,
    ExpiryDate DATE NULL,
    PRIMARY KEY (StudentCertID),
    INDEX idx_studentcert_student (StudentID),
    INDEX idx_studentcert_cert (CertID),
    FOREIGN KEY (StudentID) REFERENCES Student(StudentID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CertID) REFERENCES Certifications(CertID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Enrollment(
	EnrollmentID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    StudentID INT UNSIGNED NOT NULL,
    CourseID INT UNSIGNED NOT NULL,
    EnrollDate DATE NOT NULL,
    EndDate DATE NULL,
    CompletionStatus ENUM('Enrolled', 'Passed', 'Dropped', 'Failed') NOT NULL DEFAULT 'Enrolled',
    PRIMARY KEY (EnrollmentID),
    INDEX idx_enroll_student (StudentID),
    INDEX idx_enroll_course (CourseID),
    FOREIGN KEY (StudentID) REFERENCES Student(StudentID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (CourseID) REFERENCES Courses(CourseID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE Users(
	UserID INT UNSIGNED AUTO_INCREMENT,
    Username VARCHAR(64) NOT NULL UNIQUE,
    UserEmail VARCHAR(255) NOT NULL UNIQUE,
    UserPassword VARCHAR(255) NOT NULL,
    CreatedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LastLogin TIMESTAMP NULL,
    PRIMARY KEY (UserID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;